#include "engine/framework/text/chinese_variant.h"

#include "engine/framework/text/utf8.h"

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace engine::text {
namespace {

std::string to_lower_ascii(std::string_view value) {
    std::string out;
    out.reserve(value.size());
    for (char ch : value) {
        out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(ch))));
    }
    return out;
}

std::string trim_ascii(std::string_view value) {
    size_t start = 0;
    while (start < value.size() && std::isspace(static_cast<unsigned char>(value[start]))) {
        ++start;
    }
    size_t end = value.size();
    while (end > start && std::isspace(static_cast<unsigned char>(value[end - 1]))) {
        --end;
    }
    return std::string(value.substr(start, end - start));
}

// OpenCC TSCharacters.txt – Traditional -> Simplified single-char mapping.
// Generated by /tmp/gen_mapping.py from https://raw.githubusercontent.com/BYVoid/OpenCC/master/data/dictionary/TSCharacters.txt
const std::unordered_map<uint32_t, uint32_t> & t2s_map() {
    static const std::unordered_map<uint32_t, uint32_t> map = {
#include "chinese_variant_data.inc"
    };
    return map;
}

std::vector<uint32_t> decode_utf8_strict(std::string_view text, const char * label) {
    std::vector<uint32_t> out;
    out.reserve(text.size());
    for (size_t i = 0; i < text.size();) {
        unsigned char c = static_cast<unsigned char>(text[i]);
        uint32_t cp = 0;
        size_t len = 0;
        if (c < 0x80) {
            cp = c;
            len = 1;
        } else if ((c & 0xE0) == 0xC0) {
            cp = c & 0x1F;
            len = 2;
        } else if ((c & 0xF0) == 0xE0) {
            cp = c & 0x0F;
            len = 3;
        } else if ((c & 0xF8) == 0xF0) {
            cp = c & 0x07;
            len = 4;
        } else {
            throw std::runtime_error(std::string(label) + " contains invalid UTF-8");
        }
        if (i + len > text.size()) {
            throw std::runtime_error(std::string(label) + " contains truncated UTF-8");
        }
        for (size_t j = 1; j < len; ++j) {
            unsigned char cc = static_cast<unsigned char>(text[i + j]);
            if ((cc & 0xC0) != 0x80) {
                throw std::runtime_error(std::string(label) + " contains invalid UTF-8 continuation byte");
            }
            cp = (cp << 6) | (cc & 0x3F);
        }
        out.push_back(cp);
        i += len;
    }
    return out;
}

std::string encode_utf8_codepoints(const std::vector<uint32_t> & cps) {
    std::string out;
    out.reserve(cps.size() * 3);
    for (uint32_t cp : cps) {
        if (cp < 0x80) {
            out.push_back(static_cast<char>(cp));
        } else if (cp < 0x800) {
            out.push_back(static_cast<char>(0xC0 | (cp >> 6)));
            out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
        } else if (cp < 0x10000) {
            out.push_back(static_cast<char>(0xE0 | (cp >> 12)));
            out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
            out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
        } else {
            out.push_back(static_cast<char>(0xF0 | (cp >> 18)));
            out.push_back(static_cast<char>(0x80 | ((cp >> 12) & 0x3F)));
            out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
            out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
        }
    }
    return out;
}

}  // namespace

bool is_cantonese_language(std::string_view language) noexcept {
    std::string lang = to_lower_ascii(trim_ascii(language));
    if (lang.empty() || lang == "auto") {
        return false;
    }
    // Normalize separators to '-'
    for (char & ch : lang) {
        if (ch == '_') {
            ch = '-';
        }
    }
    // Direct tags
    if (lang == "yue" || lang == "yue-hant" || lang == "yue-hans" ||
        lang == "zh-yue" || lang == "zh-hk" || lang == "zh-mo" ||
        lang == "zh-hant-hk" || lang == "zh-hant-mo" ||
        lang == "cantonese") {
        return true;
    }
    // Substring heuristics: any "yue" or "cantonese" or "hk"/"mo" as cantonese region
    if (lang.find("yue") != std::string::npos) {
        return true;
    }
    if (lang.find("cantonese") != std::string::npos) {
        return true;
    }
    // zh-Hant alone is not necessarily Cantonese (Taiwan also uses Hant),
    // so only hk/mo are treated as Cantonese.
    if (lang == "hk" || lang == "mo" || lang == "zh-hant") {
        // zh-Hant without region is ambiguous (Taiwan uses Hant for Mandarin),
        // so do NOT treat as Cantonese to avoid false positives.
        // Only hk/mo are Cantonese.
        return false;
    }
    return false;
}

bool contains_traditional_characters(std::string_view text) {
    const auto & map = t2s_map();
    auto cps = decode_utf8_strict(text, "chinese variant text");
    for (uint32_t cp : cps) {
        if (map.find(cp) != map.end()) {
            return true;
        }
    }
    return false;
}

std::string convert_traditional_to_simplified(std::string_view text) {
    const auto & map = t2s_map();
    auto cps = decode_utf8_strict(text, "chinese variant text");
    bool changed = false;
    for (uint32_t & cp : cps) {
        auto it = map.find(cp);
        if (it != map.end()) {
            cp = it->second;
            changed = true;
        }
    }
    if (!changed) {
        return std::string(text);
    }
    return encode_utf8_codepoints(cps);
}

std::string maybe_convert_traditional_to_simplified(
    std::string_view text,
    std::string_view language) {
    if (is_cantonese_language(language)) {
        // Keep Traditional for Cantonese
        return std::string(text);
    }
    return convert_traditional_to_simplified(text);
}



}  // namespace engine::text
